### ISSUE TITLE
date/time field value out of range when exporting to postgres

### ISSUE THREAD

**Issue by dnightbane** [EQAditu/AdvancedCombatTracker#37]
When trying to export data from ACT (Version 3.5.0.273) and FFXIV Plugin (Version 2.2.1.6) to a postgres (Version 12.8) database, I am getting the following message:

`System.Data.Odbc.OdbcException (0x80131937): ERROR [22008] ERROR: date/time field value out of range: "0000-00-00 00:00:00";`

Log Excerpt below and full log attached. I've tried searching within the log to see if it's in the actual data but couldn't find anything so I'm not sure where the issue is occurring.

```
***** 2021-11-13T18:51:31 - INSERT INTO current_table (encid,ally,name,starttime,endtime,duration,damage,damageperc,kills,healed,healedperc,critheals,heals,curedispels,powerdrain,powerreplenish,dps,encdps,enchps,hits,crithits,blocked,misses,swings,healstaken,damagetaken,deaths,tohit,critdamperc,crithealperc,crittypes,threatstr,threatdelta,job,parrypct,blockpct,inctohit,overhealpct,directhitpct,directhitcount,critdirecthitcount,critdirecthitpct) VALUES ('', 'F', 'Draconic Regard', '0000-00-00 00:00:00', '0000-00-00 00:00:00', '0', '0', '--', '0', '0', '--', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '234768', '3', '0', '0%', '0%', '-', '+(0)0/-(0)0', '0', '', '0%', '0%', '100.00', '0%', '0.0%', '0', '0', '0.0%');
System.Data.Odbc.OdbcException (0x80131937): ERROR [22008] ERROR: date/time field value out of range: "0000-00-00 00:00:00";
Error while executing the query
   at System.Data.Odbc.OdbcConnection.HandleError(OdbcHandle hrHandle, RetCode retcode)
   at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader, Object[] methodArguments, SQL_API odbcApiMethod)
   at System.Data.Odbc.OdbcCommand.ExecuteReaderObject(CommandBehavior behavior, String method, Boolean needReader)
   at System.Data.Odbc.OdbcCommand.ExecuteNonQuery()
   at Advanced_Combat_Tracker.FormActMain.GenerateCurrentOdbc()
   at Advanced_Combat_Tracker.FormActMain.WriteExceptionLog(Exception ex, String MoreInfo)
   at Advanced_Combat_Tracker.FormActMain.GenerateCurrentOdbc()
   at Advanced_Combat_Tracker.FormActMain.tmrTick_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at Advanced_Combat_Tracker.ActLoader.Main(String[] args)
*****
```

[Network_22106_20211117.log](https://github.com/EQAditu/AdvancedCombatTracker/files/7566647/Network_22106_20211117.log)

**Comment by EQAditu** [comment]
Some database engines are okay with that value, some not.  The DataSource Compatibility Hacks section is specifically for working around different engines wanting different things.  You can click the **Reset** button and it will pre-populate some.

![image](https://user-images.githubusercontent.com/52854036/142515364-07046a83-4674-4890-a6b1-df77f1e3dab6.png)

You could instead change the **Replace** value to null if the column type supports it.
