### ISSUE TITLE
(EQ2) Event Handler Unhandled Exceptions - Post update 14/04/2022

### ISSUE THREAD

**Issue by xApathy** [EQAditu/AdvancedCombatTracker#47]
Hello,

I keep getting ACT pop up on EQ2 with the subject line above as error message.

Along with

"In the last minute, these plugins caused exceptions in event handlers:

ACT_English_Parser.cs-637855412879426198, Version=1.4.0.26, Culture=neutral, PublicKeyToken=null [124 time(s)]"

Looking through my combat log, I do not see shortened combat damage values (M, K, etc.) and I was running in a lvl 70 zone, so powercreep was not as high then. 

This is the ACT.log, an excerpt anyway.

***** 2022-04-14T10:17:18 - BeforeLogLineRead event
(1649895438)[Thu Apr 14 10:17:18 2022] Mouse's Headache hits a chokidai handler for 2,444 mental damage.
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at ACT_Plugin.ACT_English_Parser.DamageAndType..ctor(String UnsplitSource) in c:\Users\pfort\AppData\Roaming\Advanced Combat Tracker\Plugins\ACT_English_Parser.cs:line 1630
   at ACT_Plugin.ACT_English_Parser.EngGetDamageAndTypeArr(String damageAndType) in c:\Users\pfort\AppData\Roaming\Advanced Combat Tracker\Plugins\ACT_English_Parser.cs:line 1223
   at ACT_Plugin.ACT_English_Parser.LogExeEnglish(Match reMatch, Int32 logMatched, String logLine, Boolean isImport) in c:\Users\pfort\AppData\Roaming\Advanced Combat Tracker\Plugins\ACT_English_Parser.cs:line 461
   at ACT_Plugin.ACT_English_Parser.oFormActMain_BeforeLogLineRead(Boolean isImport, LogLineEventArgs logInfo) in c:\Users\pfort\AppData\Roaming\Advanced Combat Tracker\Plugins\ACT_English_Parser.cs:line 379
   at Advanced_Combat_Tracker.FormActMain.ParseRawLogLine(Boolean isImport, DateTime ParsedLogTime, String LogLine, String CompanionLogName)
   at Advanced_Combat_Tracker.FormActMain.WriteExceptionLog(Exception ex, String MoreInfo)
   at Advanced_Combat_Tracker.FormActMain.ParseRawLogLine(Boolean isImport, DateTime ParsedLogTime, String LogLine, String CompanionLogName)
   at Advanced_Combat_Tracker.FormActMain.ReadLog()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
*****

**Comment by xApathy** [comment]
https://imgur.com/lR453tq

**Comment by EQAditu** [comment]
You need to use v1.4.1.27 of the parsing plugin or turn off formatted / abbreviated numbers in the game client.  "2,444" is an example of a formatted number.

**Comment by EQAditu** [comment]
As far as I know, the newest version of the EQ2 English parsing plugin addresses the issues.
